# Generated by Django 4.2.30 on 2026-06-21 12:54

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        ("teams", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="RiskLog",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "risk_level",
                    models.CharField(
                        choices=[
                            ("normal", "正常推进"),
                            ("attention", "需要关注"),
                            ("critical", "需要介入"),
                        ],
                        max_length=20,
                        verbose_name="风险等级",
                    ),
                ),
                (
                    "risk_type",
                    models.CharField(blank=True, max_length=100, verbose_name="风险类型"),
                ),
                ("description", models.TextField(verbose_name="风险描述")),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("open", "待处理"),
                            ("in_progress", "处理中"),
                            ("resolved", "已解决"),
                        ],
                        default="open",
                        max_length=20,
                        verbose_name="处理状态",
                    ),
                ),
                ("action_plan", models.TextField(blank=True, verbose_name="处理计划")),
                (
                    "next_action",
                    models.CharField(blank=True, max_length=300, verbose_name="下一步动作"),
                ),
                (
                    "reminder_time",
                    models.DateTimeField(blank=True, null=True, verbose_name="提醒时间"),
                ),
                (
                    "resolved_at",
                    models.DateTimeField(blank=True, null=True, verbose_name="解决时间"),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "created_by",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="created_risks",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="创建人",
                    ),
                ),
                (
                    "owner",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="owned_risks",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="责任人",
                    ),
                ),
                (
                    "team",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="risk_logs",
                        to="teams.team",
                    ),
                ),
            ],
            options={
                "verbose_name": "风险记录",
                "verbose_name_plural": "风险记录",
                "ordering": ["-updated_at"],
            },
        ),
        migrations.CreateModel(
            name="ActivityLog",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("action", models.CharField(max_length=200, verbose_name="动作")),
                ("description", models.TextField(verbose_name="描述")),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "team",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="activities",
                        to="teams.team",
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "活动日志",
                "verbose_name_plural": "活动日志",
                "ordering": ["-created_at"],
            },
        ),
    ]
