# Generated by Django 5.2.15 on 2026-07-13 06:02

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        ("teams", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="LeanCanvas",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("problem", models.TextField(blank=True)),
                ("existing_alternatives", models.TextField(blank=True)),
                ("solution", models.TextField(blank=True)),
                ("key_metrics", models.TextField(blank=True)),
                ("unique_value_proposition", models.TextField(blank=True)),
                ("high_level_concept", models.TextField(blank=True)),
                ("sustainable_advantage", models.TextField(blank=True)),
                ("channels", models.TextField(blank=True)),
                ("customer_segments", models.TextField(blank=True)),
                ("early_adopters", models.TextField(blank=True)),
                ("cost_structure", models.TextField(blank=True)),
                ("revenue_streams", models.TextField(blank=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "team",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="lean_canvas",
                        to="teams.team",
                    ),
                ),
            ],
        ),
    ]
