# Generated by Django 5.2.15 on 2026-07-13 12:52

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("bmc", "0002_coalesce_null_text_fields"),
    ]

    operations = [
        migrations.AlterField(
            model_name="leancanvas",
            name="channels",
            field=models.TextField(blank=True, default=""),
        ),
        migrations.AlterField(
            model_name="leancanvas",
            name="cost_structure",
            field=models.TextField(blank=True, default=""),
        ),
        migrations.AlterField(
            model_name="leancanvas",
            name="customer_segments",
            field=models.TextField(blank=True, default=""),
        ),
        migrations.AlterField(
            model_name="leancanvas",
            name="early_adopters",
            field=models.TextField(blank=True, default=""),
        ),
        migrations.AlterField(
            model_name="leancanvas",
            name="existing_alternatives",
            field=models.TextField(blank=True, default=""),
        ),
        migrations.AlterField(
            model_name="leancanvas",
            name="high_level_concept",
            field=models.TextField(blank=True, default=""),
        ),
        migrations.AlterField(
            model_name="leancanvas",
            name="key_metrics",
            field=models.TextField(blank=True, default=""),
        ),
        migrations.AlterField(
            model_name="leancanvas",
            name="problem",
            field=models.TextField(blank=True, default=""),
        ),
        migrations.AlterField(
            model_name="leancanvas",
            name="revenue_streams",
            field=models.TextField(blank=True, default=""),
        ),
        migrations.AlterField(
            model_name="leancanvas",
            name="solution",
            field=models.TextField(blank=True, default=""),
        ),
        migrations.AlterField(
            model_name="leancanvas",
            name="sustainable_advantage",
            field=models.TextField(blank=True, default=""),
        ),
        migrations.AlterField(
            model_name="leancanvas",
            name="unique_value_proposition",
            field=models.TextField(blank=True, default=""),
        ),
    ]
