# Generated by Django 5.x

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("bmc", "0003_alter_leancanvas_channels_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="leancanvas",
            name="field_reviews",
            field=models.JSONField(blank=True, default=dict),
        ),
    ]
