# Generated by Django 4.2.30 on 2026-06-21 12:54

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        ("teams", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="LessonRecord",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("lesson_time", models.DateTimeField(verbose_name="上课时间")),
                ("duration", models.IntegerField(default=90, verbose_name="时长(分钟)")),
                ("topic", models.CharField(max_length=300, verbose_name="课程主题")),
                ("lesson_goal", models.TextField(blank=True, verbose_name="本节课目标")),
                (
                    "completed_content",
                    models.TextField(blank=True, verbose_name="实际完成内容"),
                ),
                (
                    "student_attendance",
                    models.CharField(blank=True, max_length=200, verbose_name="学生出勤"),
                ),
                (
                    "student_performance",
                    models.TextField(blank=True, verbose_name="学生课堂表现"),
                ),
                (
                    "project_progress",
                    models.TextField(blank=True, verbose_name="项目推进情况"),
                ),
                ("homework", models.TextField(blank=True, verbose_name="课后任务")),
                (
                    "next_lesson_plan",
                    models.TextField(blank=True, verbose_name="下节课计划"),
                ),
                ("risk_notes", models.TextField(blank=True, verbose_name="当前风险")),
                (
                    "admin_score",
                    models.FloatField(blank=True, null=True, verbose_name="教务评分"),
                ),
                (
                    "mentor_feedback",
                    models.TextField(blank=True, verbose_name="导师课后反馈"),
                ),
                (
                    "mentor_feedback_status",
                    models.CharField(
                        choices=[
                            ("pending", "待提交"),
                            ("submitted", "已提交"),
                            ("overdue", "已逾期"),
                        ],
                        default="pending",
                        max_length=20,
                        verbose_name="反馈状态",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "academic_admin",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="admin_lessons",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="教务老师",
                    ),
                ),
                (
                    "mentor",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="mentor_lessons",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="授课导师",
                    ),
                ),
                (
                    "stage",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to="teams.stage",
                    ),
                ),
                (
                    "team",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="lessons",
                        to="teams.team",
                    ),
                ),
            ],
            options={
                "verbose_name": "课堂记录",
                "verbose_name_plural": "课堂记录",
                "ordering": ["-lesson_time"],
            },
        ),
        migrations.CreateModel(
            name="CalendarEvent",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("start_time", models.DateTimeField(verbose_name="开始时间")),
                ("end_time", models.DateTimeField(verbose_name="结束时间")),
                ("topic", models.CharField(max_length=300, verbose_name="课程主题")),
                (
                    "feedback_submitted",
                    models.BooleanField(default=False, verbose_name="已提交反馈"),
                ),
                (
                    "is_cancelled",
                    models.BooleanField(default=False, verbose_name="已取消"),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "academic_admin",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="admin_calendar_events",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="教务老师",
                    ),
                ),
                (
                    "mentor",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="calendar_events",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="授课导师",
                    ),
                ),
                (
                    "stage",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to="teams.stage",
                    ),
                ),
                (
                    "team",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="calendar_events",
                        to="teams.team",
                    ),
                ),
            ],
            options={
                "verbose_name": "课程安排",
                "verbose_name_plural": "课程安排",
                "ordering": ["start_time"],
            },
        ),
    ]
