# Generated by Django 4.2.30 on 2026-06-21 12:54

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        ("teams", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="TeamScore",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "project_clarity",
                    models.FloatField(default=0, verbose_name="项目方向清晰度"),
                ),
                (
                    "technical_feasibility",
                    models.FloatField(default=0, verbose_name="技术方案可行性"),
                ),
                (
                    "business_model",
                    models.FloatField(default=0, verbose_name="商业模式完整度"),
                ),
                (
                    "market_research",
                    models.FloatField(default=0, verbose_name="市场调研质量"),
                ),
                (
                    "prototype_quality",
                    models.FloatField(default=0, verbose_name="产品原型完成度"),
                ),
                (
                    "pitch_deck_quality",
                    models.FloatField(default=0, verbose_name="PPT表达质量"),
                ),
                ("video_quality", models.FloatField(default=0, verbose_name="视频完成度")),
                ("website_quality", models.FloatField(default=0, verbose_name="网站完成度")),
                ("qa_preparation", models.FloatField(default=0, verbose_name="答辩准备度")),
                ("teamwork", models.FloatField(default=0, verbose_name="团队协作度")),
                ("execution", models.FloatField(default=0, verbose_name="学生执行力")),
                (
                    "final_competitiveness",
                    models.FloatField(default=0, verbose_name="最终竞赛竞争力"),
                ),
                ("total_score", models.FloatField(default=0, verbose_name="总分")),
                ("strengths", models.TextField(blank=True, verbose_name="队伍优势")),
                ("weaknesses", models.TextField(blank=True, verbose_name="当前短板")),
                ("suggestions", models.TextField(blank=True, verbose_name="提升建议")),
                ("comments", models.TextField(blank=True, verbose_name="项目经理备注")),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "evaluated_by",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="team_scores_given",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="评分人",
                    ),
                ),
                (
                    "team",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="team_scores",
                        to="teams.team",
                    ),
                ),
            ],
            options={
                "verbose_name": "队伍评分",
                "verbose_name_plural": "队伍评分",
                "ordering": ["-total_score"],
            },
        ),
        migrations.CreateModel(
            name="TeacherEvaluation",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "season",
                    models.CharField(
                        default="2026-2027", max_length=50, verbose_name="赛季"
                    ),
                ),
                ("score_a", models.FloatField(default=0, verbose_name="阶段交付物完成度")),
                ("score_b", models.FloatField(default=0, verbose_name="课堂质量与项目推进")),
                ("score_c", models.FloatField(default=0, verbose_name="课前备课与课后反馈")),
                ("score_d", models.FloatField(default=0, verbose_name="团队管理与沟通配合")),
                ("score_e", models.FloatField(default=0, verbose_name="最终成果与竞赛表现")),
                ("total_score", models.FloatField(default=0, verbose_name="总分")),
                (
                    "level",
                    models.CharField(blank=True, max_length=2, verbose_name="等级"),
                ),
                ("comments", models.TextField(blank=True, verbose_name="评语")),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "evaluated_by",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="evaluations_given",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="评分人",
                    ),
                ),
                (
                    "mentor",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="teacher_evaluations",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="导师",
                    ),
                ),
                (
                    "team",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="teacher_evaluations",
                        to="teams.team",
                    ),
                ),
            ],
            options={
                "verbose_name": "导师评分",
                "verbose_name_plural": "导师评分",
                "ordering": ["-total_score"],
            },
        ),
    ]
