# Generated by Django 5.2.15 on 2026-06-28 10:55

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        ("teams", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="InnovationBrief",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("problem_statement", models.TextField(blank=True)),
                ("target_users", models.TextField(blank=True)),
                ("existing_solutions", models.TextField(blank=True)),
                ("our_solution", models.TextField(blank=True)),
                ("innovation_points", models.TextField(blank=True)),
                ("technical_design", models.TextField(blank=True)),
                ("prototype_testing", models.TextField(blank=True)),
                ("market_business", models.TextField(blank=True)),
                ("social_impact", models.TextField(blank=True)),
                ("team_roles_next_steps", models.TextField(blank=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "team",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="innovation_brief",
                        to="teams.team",
                    ),
                ),
            ],
        ),
    ]
