# Generated by Django 5.2.15 on 2026-07-13 12:52

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("briefs", "0003_coalesce_null_text_fields"),
    ]

    operations = [
        migrations.AlterField(
            model_name="innovationbrief",
            name="business_model",
            field=models.TextField(blank=True, default=""),
        ),
        migrations.AlterField(
            model_name="innovationbrief",
            name="competition",
            field=models.TextField(blank=True, default=""),
        ),
        migrations.AlterField(
            model_name="innovationbrief",
            name="elevator_pitch",
            field=models.TextField(blank=True, default=""),
        ),
        migrations.AlterField(
            model_name="innovationbrief",
            name="fundraising",
            field=models.TextField(blank=True, default=""),
        ),
        migrations.AlterField(
            model_name="innovationbrief",
            name="go_to_market",
            field=models.TextField(blank=True, default=""),
        ),
        migrations.AlterField(
            model_name="innovationbrief",
            name="key_metrics",
            field=models.TextField(blank=True, default=""),
        ),
        migrations.AlterField(
            model_name="innovationbrief",
            name="market",
            field=models.TextField(blank=True, default=""),
        ),
        migrations.AlterField(
            model_name="innovationbrief",
            name="opportunity",
            field=models.TextField(blank=True, default=""),
        ),
        migrations.AlterField(
            model_name="innovationbrief",
            name="team_overview",
            field=models.TextField(blank=True, default=""),
        ),
        migrations.AlterField(
            model_name="innovationbrief",
            name="validation_progress",
            field=models.TextField(blank=True, default=""),
        ),
    ]
