# Generated by Django 5.x

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("briefs", "0004_alter_innovationbrief_business_model_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="innovationbrief",
            name="field_reviews",
            field=models.JSONField(blank=True, default=dict),
        ),
    ]
