import {
  AlignmentType,
  Document,
  HeadingLevel,
  Packer,
  Paragraph,
  TextRun,
  BorderStyle,
  Table,
  TableRow,
  TableCell,
  WidthType,
} from "docx";
import { saveAs } from "file-saver";
import { BMC_QUESTIONS, type LeanCanvas } from "@/types/bmc";
import { isRichTextEmpty, stripHtml } from "@/utils/richText";

export interface BmcExportMeta {
  teamName: string;
  projectName: string;
  challengeCategory?: string;
  teacherName?: string;
}

function safeFilename(name: string): string {
  return name.replace(/[/\\?%*:|"<>]/g, "_").trim() || "Lean_Canvas";
}

function formatExportDate(): string {
  return new Date().toLocaleString("zh-CN", {
    year: "numeric",
    month: "2-digit",
    day: "2-digit",
    hour: "2-digit",
    minute: "2-digit",
  });
}

function escapeHtml(text: string): string {
  return text
    .replace(/&/g, "&amp;")
    .replace(/</g, "&lt;")
    .replace(/>/g, "&gt;")
    .replace(/"/g, "&quot;");
}

function answerHtml(value: string): string {
  if (!value || isRichTextEmpty(value)) {
    return '<p class="empty">（未填写 / Not provided）</p>';
  }
  return value;
}

function buildExportHtml(canvas: LeanCanvas, meta: BmcExportMeta, pdfSafe = false): string {
  const exportedAt = formatExportDate();
  const e = escapeHtml;
  const sections = BMC_QUESTIONS.map((q) => {
    const val = String(canvas[q.id] || "");
    return `
      <section class="question-block">
        <div class="question-head">
          <span class="q-badge">Q${q.q}</span>
          <div class="question-titles">
            <h2 class="q-title">${e(q.titleEn)}</h2>
            <p class="q-subtitle">${e(q.titleZh)}</p>
          </div>
        </div>
        <div class="answer rich-content">${answerHtml(val)}</div>
      </section>
    `;
  }).join("");

  const coverStyle = pdfSafe
    ? "background:#d97706;"
    : "background:linear-gradient(135deg,#f59e0b 0%,#d97706 100%);";
  const metaStyle = pdfSafe
    ? "display:block;"
    : "display:grid;grid-template-columns:1fr 1fr;gap:12px 24px;";
  const metaItemStyle = pdfSafe
    ? "display:inline-block;width:48%;vertical-align:top;margin-bottom:10px;"
    : "";
  const badgeStyle = pdfSafe ? "float:left;margin-right:12px;" : "";

  return `
    <div class="bmc-export-root">
      <header class="cover" style="${coverStyle}">
        <p class="brand">CONRAD CHALLENGE · STEMHUB</p>
        <h1 class="doc-title">Lean Canvas · BMC</h1>
        <p class="doc-subtitle">精益画布 · 商业模式画布</p>
        <div class="meta-grid" style="${metaStyle}">
          <div style="${metaItemStyle}"><span class="label">Team / 队伍</span><strong>${e(meta.teamName)}</strong></div>
          <div style="${metaItemStyle}"><span class="label">Project / 项目</span><strong>${e(meta.projectName)}</strong></div>
          ${
            meta.challengeCategory
              ? `<div style="${metaItemStyle}"><span class="label">Category / 类别</span><strong>${e(meta.challengeCategory)}</strong></div>`
              : ""
          }
          ${
            meta.teacherName
              ? `<div style="${metaItemStyle}"><span class="label">Teacher / 带队老师</span><strong>${e(meta.teacherName)}</strong></div>`
              : ""
          }
          <div style="${metaItemStyle}"><span class="label">Completion / 完成度</span><strong>${canvas.completion_count} / 12</strong></div>
          <div style="${metaItemStyle}"><span class="label">Exported / 导出时间</span><strong>${e(exportedAt)}</strong></div>
        </div>
      </header>
      <main>${sections}</main>
      <footer class="footer">
        <p>Conrad Challenge Lean Canvas · Generated by STEMHUB Operations</p>
      </footer>
    </div>
    <style>
      .bmc-export-root {
        font-family: -apple-system, BlinkMacSystemFont, "Segoe UI", "PingFang SC", "Noto Sans SC", sans-serif;
        color: #0f172a;
        line-height: 1.65;
        font-size: 11pt;
        background: #fff;
        width: 794px;
        box-sizing: border-box;
        padding: 0;
        margin: 0;
      }
      .cover {
        color: #fff;
        padding: 28px 32px 32px;
        border-radius: 12px;
        margin-bottom: 24px;
      }
      .brand {
        font-size: 9pt;
        letter-spacing: 0.12em;
        opacity: 0.9;
        margin: 0 0 12px;
        text-transform: uppercase;
      }
      .doc-title {
        font-size: 26pt;
        margin: 0;
        font-weight: 700;
        letter-spacing: -0.02em;
      }
      .doc-subtitle {
        margin: 4px 0 20px;
        font-size: 13pt;
        opacity: 0.92;
      }
      .meta-grid {
        background: rgba(255,255,255,0.12);
        border-radius: 10px;
        padding: 16px 18px;
      }
      .meta-grid .label {
        display: block;
        font-size: 8.5pt;
        opacity: 0.8;
        margin-bottom: 2px;
      }
      .meta-grid strong { font-size: 10.5pt; font-weight: 600; }
      .question-block {
        margin-bottom: 20px;
        border: 1px solid #e2e8f0;
        border-radius: 10px;
        overflow: hidden;
      }
      .question-head {
        padding: 14px 16px;
        background: #fffbeb;
        border-bottom: 3px solid #d97706;
        ${pdfSafe ? "" : "display:flex;align-items:flex-start;gap:12px;"}
      }
      .q-badge {
        width: 32px;
        height: 32px;
        line-height: 32px;
        text-align: center;
        border-radius: 8px;
        background: #fef3c7;
        color: #b45309;
        font-weight: 700;
        font-size: 11pt;
        ${badgeStyle}
      }
      .question-titles { overflow: hidden; }
      .q-title {
        margin: 0;
        font-size: 12pt;
        font-weight: 700;
        color: #0f172a;
      }
      .q-subtitle {
        margin: 2px 0 0;
        font-size: 9.5pt;
        color: #64748b;
      }
      .answer {
        padding: 16px 18px 18px;
        min-height: 48px;
      }
      .answer.empty, .empty { color: #94a3b8; font-style: italic; }
      .rich-content p { margin: 0 0 8px; }
      .rich-content ul, .rich-content ol { margin: 8px 0; padding-left: 1.4em; }
      .rich-content li { margin: 4px 0; }
      .rich-content strong { font-weight: 600; }
      .footer {
        margin-top: 28px;
        padding-top: 12px;
        border-top: 1px solid #e2e8f0;
        text-align: center;
        font-size: 8.5pt;
        color: #94a3b8;
      }
    </style>
  `;
}

function collectTextRuns(node: Node, style: { bold?: boolean; italics?: boolean } = {}): TextRun[] {
  const runs: TextRun[] = [];
  if (node.nodeType === Node.TEXT_NODE) {
    const text = node.textContent || "";
    if (text) runs.push(new TextRun({ text, bold: style.bold, italics: style.italics }));
    return runs;
  }
  if (node.nodeType !== Node.ELEMENT_NODE) return runs;
  const el = node as HTMLElement;
  const tag = el.tagName.toUpperCase();
  if (tag === "BR") {
    runs.push(new TextRun({ break: 1 }));
    return runs;
  }
  const nextStyle = {
    bold: style.bold || tag === "STRONG" || tag === "B",
    italics: style.italics || tag === "EM" || tag === "I",
  };
  el.childNodes.forEach((child) => {
    runs.push(...collectTextRuns(child, nextStyle));
  });
  return runs;
}

function htmlToDocxParagraphs(html: string): Paragraph[] {
  if (!html || isRichTextEmpty(html)) {
    return [
      new Paragraph({
        children: [new TextRun({ text: "（未填写 / Not provided）", italics: true, color: "94A3B8" })],
      }),
    ];
  }
  const doc = new DOMParser().parseFromString(html, "text/html");
  const paragraphs: Paragraph[] = [];
  const blockTags = new Set(["P", "DIV", "LI", "H1", "H2", "H3"]);

  doc.body.childNodes.forEach((node) => {
    if (node.nodeType === Node.ELEMENT_NODE) {
      const el = node as HTMLElement;
      const tag = el.tagName.toUpperCase();
      if (tag === "UL" || tag === "OL") {
        el.querySelectorAll("li").forEach((li) => {
          const runs = collectTextRuns(li);
          paragraphs.push(
            new Paragraph({
              children: [new TextRun({ text: "• ", bold: true }), ...runs],
              spacing: { after: 120 },
            })
          );
        });
        return;
      }
      if (blockTags.has(tag) || el.textContent?.trim()) {
        const runs = collectTextRuns(el);
        if (runs.length) {
          paragraphs.push(new Paragraph({ children: runs, spacing: { after: 160 } }));
        }
      }
    } else if (node.textContent?.trim()) {
      paragraphs.push(
        new Paragraph({ children: [new TextRun(node.textContent || "")], spacing: { after: 160 } })
      );
    }
  });

  if (!paragraphs.length) {
    paragraphs.push(
      new Paragraph({ children: [new TextRun(stripHtml(html))], spacing: { after: 160 } })
    );
  }
  return paragraphs;
}

function noBorders() {
  const none = { style: BorderStyle.NONE, size: 0, color: "FFFFFF" };
  return { top: none, bottom: none, left: none, right: none };
}

function metaTableRows(meta: BmcExportMeta, canvas: LeanCanvas): TableRow[] {
  const rows: [string, string][] = [
    ["Team / 队伍", meta.teamName],
    ["Project / 项目", meta.projectName],
  ];
  if (meta.challengeCategory) rows.push(["Category / 类别", meta.challengeCategory]);
  if (meta.teacherName) rows.push(["Teacher / 带队老师", meta.teacherName]);
  rows.push(["Completion / 完成度", `${canvas.completion_count} / 12`]);
  rows.push(["Exported / 导出时间", formatExportDate()]);

  return rows.map(
    ([label, value]) =>
      new TableRow({
        children: [
          new TableCell({
            width: { size: 35, type: WidthType.PERCENTAGE },
            children: [new Paragraph({ children: [new TextRun({ text: label, color: "64748B", size: 20 })] })],
            borders: noBorders(),
          }),
          new TableCell({
            width: { size: 65, type: WidthType.PERCENTAGE },
            children: [new Paragraph({ children: [new TextRun({ text: value, bold: true, size: 22 })] })],
            borders: noBorders(),
          }),
        ],
      })
  );
}

function waitForLayout(): Promise<void> {
  return new Promise((resolve) => {
    requestAnimationFrame(() => requestAnimationFrame(() => resolve()));
  });
}

function mountPdfFrame(html: string): { root: HTMLElement; cleanup: () => void } {
  const iframe = document.createElement("iframe");
  iframe.setAttribute("title", "bmc-pdf-export");
  Object.assign(iframe.style, {
    position: "fixed",
    left: "0",
    top: "0",
    width: "794px",
    border: "none",
    zIndex: "2147483647",
    opacity: "0.01",
    pointerEvents: "none",
  });
  document.body.appendChild(iframe);

  const doc = iframe.contentDocument || iframe.contentWindow?.document;
  if (!doc) {
    document.body.removeChild(iframe);
    throw new Error("无法创建 PDF 渲染环境");
  }

  doc.open();
  doc.write(
    `<!DOCTYPE html><html><head><meta charset="utf-8"></head><body style="margin:0;padding:0;background:#fff;">${html}</body></html>`
  );
  doc.close();

  const root = doc.querySelector(".bmc-export-root") as HTMLElement | null;
  if (!root) {
    document.body.removeChild(iframe);
    throw new Error("导出内容加载失败");
  }

  iframe.style.height = `${Math.max(doc.body.scrollHeight, root.scrollHeight) + 20}px`;

  return {
    root,
    cleanup: () => {
      if (iframe.parentNode) document.body.removeChild(iframe);
    },
  };
}

async function canvasToPdf(canvasEl: HTMLCanvasElement, filename: string): Promise<void> {
  const { jsPDF } = await import("jspdf");
  const pdf = new jsPDF({ orientation: "portrait", unit: "mm", format: "a4" });

  const pageWidth = pdf.internal.pageSize.getWidth();
  const pageHeight = pdf.internal.pageSize.getHeight();
  const margin = 8;
  const contentWidth = pageWidth - margin * 2;
  const contentHeight = pageHeight - margin * 2;

  const imgWidth = contentWidth;
  const imgHeight = (canvasEl.height * imgWidth) / canvasEl.width;

  let heightLeft = imgHeight;
  let offsetY = 0;
  const imgData = canvasEl.toDataURL("image/jpeg", 0.92);

  pdf.addImage(imgData, "JPEG", margin, margin, imgWidth, imgHeight);
  heightLeft -= contentHeight;

  while (heightLeft > 0) {
    offsetY = heightLeft - imgHeight;
    pdf.addPage();
    pdf.addImage(imgData, "JPEG", margin, offsetY + margin, imgWidth, imgHeight);
    heightLeft -= contentHeight;
  }

  pdf.save(filename);
}

export async function exportBmcPdf(canvas: LeanCanvas, meta: BmcExportMeta): Promise<void> {
  const html = buildExportHtml(canvas, meta, true);
  const { root, cleanup } = mountPdfFrame(html);
  const filename = `${safeFilename(meta.teamName)}_Lean_Canvas_BMC.pdf`;

  try {
    await waitForLayout();
    await new Promise((r) => setTimeout(r, 120));

    const html2canvas = (await import("html2canvas")).default;
    const scale = root.scrollHeight > 10000 ? 1 : root.scrollHeight > 6000 ? 1.25 : 1.5;

    const rendered = await html2canvas(root, {
      scale,
      useCORS: true,
      logging: false,
      backgroundColor: "#ffffff",
      width: 794,
      windowWidth: 794,
      scrollX: 0,
      scrollY: 0,
    });

    if (!rendered.width || !rendered.height) {
      throw new Error("PDF 画布生成失败");
    }

    await canvasToPdf(rendered, filename);
  } finally {
    cleanup();
  }
}

export async function exportBmcDocx(canvas: LeanCanvas, meta: BmcExportMeta): Promise<void> {
  const children: (Paragraph | Table)[] = [
    new Paragraph({
      alignment: AlignmentType.CENTER,
      spacing: { after: 80 },
      children: [
        new TextRun({
          text: "CONRAD CHALLENGE · STEMHUB",
          size: 18,
          color: "64748B",
          allCaps: true,
        }),
      ],
    }),
    new Paragraph({
      heading: HeadingLevel.TITLE,
      alignment: AlignmentType.CENTER,
      children: [new TextRun({ text: "Lean Canvas · BMC", bold: true, size: 48, color: "D97706" })],
      spacing: { after: 60 },
    }),
    new Paragraph({
      alignment: AlignmentType.CENTER,
      spacing: { after: 240 },
      children: [new TextRun({ text: "精益画布 · 商业模式画布", size: 28, color: "B45309" })],
    }),
    new Table({
      width: { size: 100, type: WidthType.PERCENTAGE },
      rows: metaTableRows(meta, canvas),
    }),
    new Paragraph({ text: "", spacing: { after: 300 } }),
  ];

  BMC_QUESTIONS.forEach((q) => {
    const val = String(canvas[q.id] || "");
    children.push(
      new Paragraph({
        spacing: { before: 280, after: 120 },
        border: {
          bottom: { color: "D97706", size: 12, style: BorderStyle.SINGLE },
        },
        children: [
          new TextRun({ text: `Q${q.q}. `, bold: true, size: 26, color: "D97706" }),
          new TextRun({ text: q.titleEn, bold: true, size: 26 }),
        ],
      }),
      new Paragraph({
        spacing: { after: 160 },
        children: [new TextRun({ text: q.titleZh, italics: true, color: "64748B", size: 20 })],
      }),
      ...htmlToDocxParagraphs(val)
    );
  });

  children.push(
    new Paragraph({
      alignment: AlignmentType.CENTER,
      spacing: { before: 400 },
      children: [
        new TextRun({
          text: "Conrad Challenge Lean Canvas · STEMHUB Operations Export",
          size: 18,
          color: "94A3B8",
          italics: true,
        }),
      ],
    })
  );

  const doc = new Document({
    sections: [{ properties: {}, children }],
  });

  const blob = await Packer.toBlob(doc);
  saveAs(blob, `${safeFilename(meta.teamName)}_Lean_Canvas_BMC.docx`);
}
