import {
  AlignmentType,
  Document,
  HeadingLevel,
  Packer,
  Paragraph,
  TextRun,
  BorderStyle,
  Table,
  TableRow,
  TableCell,
  WidthType,
} from "docx";
import { saveAs } from "file-saver";
import { BRIEF_QUESTIONS, type InnovationBrief } from "@/types/brief";
import { isRichTextEmpty, stripHtml } from "@/utils/richText";

export interface BriefExportMeta {
  teamName: string;
  projectName: string;
  challengeCategory?: string;
  teacherName?: string;
}

function safeFilename(name: string): string {
  return name.replace(/[/\\?%*:|"<>]/g, "_").trim() || "Innovation_Brief";
}

function formatExportDate(): string {
  return new Date().toLocaleString("zh-CN", {
    year: "numeric",
    month: "2-digit",
    day: "2-digit",
    hour: "2-digit",
    minute: "2-digit",
  });
}

function answerHtml(value: string): string {
  if (!value || isRichTextEmpty(value)) {
    return '<p class="empty">（未填写 / Not provided）</p>';
  }
  return value;
}

function buildExportHtml(brief: InnovationBrief, meta: BriefExportMeta): string {
  const exportedAt = formatExportDate();
  const sections = BRIEF_QUESTIONS.map((q) => {
    const val = String(brief[q.id] || "");
    return `
      <section class="question-block">
        <div class="question-head">
          <span class="q-badge">Q${q.q}</span>
          <div>
            <h2 class="q-title">${q.titleEn}</h2>
            <p class="q-subtitle">${q.titleZh}</p>
          </div>
        </div>
        <div class="answer rich-content">${answerHtml(val)}</div>
      </section>
    `;
  }).join("");

  return `
    <div class="brief-export-root">
      <header class="cover">
        <p class="brand">CONRAD CHALLENGE · STEMHUB</p>
        <h1 class="doc-title">Innovation Brief</h1>
        <p class="doc-subtitle">创新简报</p>
        <div class="meta-grid">
          <div><span class="label">Team / 队伍</span><strong>${meta.teamName}</strong></div>
          <div><span class="label">Project / 项目</span><strong>${meta.projectName}</strong></div>
          ${
            meta.challengeCategory
              ? `<div><span class="label">Category / 类别</span><strong>${meta.challengeCategory}</strong></div>`
              : ""
          }
          ${
            meta.teacherName
              ? `<div><span class="label">Teacher / 带队老师</span><strong>${meta.teacherName}</strong></div>`
              : ""
          }
          <div><span class="label">Completion / 完成度</span><strong>${brief.completion_count} / 10</strong></div>
          <div><span class="label">Exported / 导出时间</span><strong>${exportedAt}</strong></div>
        </div>
      </header>
      <main>${sections}</main>
      <footer class="footer">
        <p>Conrad Challenge Innovation Brief · Generated by STEMHUB Operations</p>
      </footer>
    </div>
    <style>
      .brief-export-root {
        font-family: -apple-system, BlinkMacSystemFont, "Segoe UI", "PingFang SC", "Noto Sans SC", sans-serif;
        color: #0f172a;
        line-height: 1.65;
        font-size: 11pt;
        background: #fff;
      }
      .cover {
        background: linear-gradient(135deg, #2563eb 0%, #7c3aed 100%);
        color: #fff;
        padding: 28px 32px 32px;
        border-radius: 12px;
        margin-bottom: 24px;
      }
      .brand {
        font-size: 9pt;
        letter-spacing: 0.12em;
        opacity: 0.9;
        margin: 0 0 12px;
        text-transform: uppercase;
      }
      .doc-title {
        font-size: 26pt;
        margin: 0;
        font-weight: 700;
        letter-spacing: -0.02em;
      }
      .doc-subtitle {
        margin: 4px 0 20px;
        font-size: 13pt;
        opacity: 0.92;
      }
      .meta-grid {
        display: grid;
        grid-template-columns: 1fr 1fr;
        gap: 12px 24px;
        background: rgba(255,255,255,0.12);
        border-radius: 10px;
        padding: 16px 18px;
      }
      .meta-grid .label {
        display: block;
        font-size: 8.5pt;
        opacity: 0.8;
        margin-bottom: 2px;
      }
      .meta-grid strong { font-size: 10.5pt; font-weight: 600; }
      .question-block {
        break-inside: avoid;
        page-break-inside: avoid;
        margin-bottom: 20px;
        border: 1px solid #e2e8f0;
        border-radius: 10px;
        overflow: hidden;
      }
      .question-head {
        display: flex;
        align-items: flex-start;
        gap: 12px;
        padding: 14px 16px;
        background: #f8fafc;
        border-bottom: 3px solid #7c3aed;
      }
      .q-badge {
        flex-shrink: 0;
        width: 32px;
        height: 32px;
        line-height: 32px;
        text-align: center;
        border-radius: 8px;
        background: #ede9fe;
        color: #7c3aed;
        font-weight: 700;
        font-size: 11pt;
      }
      .q-title {
        margin: 0;
        font-size: 12pt;
        font-weight: 700;
        color: #0f172a;
      }
      .q-subtitle {
        margin: 2px 0 0;
        font-size: 9.5pt;
        color: #64748b;
      }
      .answer {
        padding: 16px 18px 18px;
        min-height: 48px;
      }
      .answer.empty, .empty { color: #94a3b8; font-style: italic; }
      .rich-content p { margin: 0 0 8px; }
      .rich-content ul, .rich-content ol { margin: 8px 0; padding-left: 1.4em; }
      .rich-content li { margin: 4px 0; }
      .rich-content strong { font-weight: 600; }
      .footer {
        margin-top: 28px;
        padding-top: 12px;
        border-top: 1px solid #e2e8f0;
        text-align: center;
        font-size: 8.5pt;
        color: #94a3b8;
      }
    </style>
  `;
}

function collectTextRuns(node: Node, style: { bold?: boolean; italics?: boolean } = {}): TextRun[] {
  const runs: TextRun[] = [];
  if (node.nodeType === Node.TEXT_NODE) {
    const text = node.textContent || "";
    if (text) runs.push(new TextRun({ text, bold: style.bold, italics: style.italics }));
    return runs;
  }
  if (node.nodeType !== Node.ELEMENT_NODE) return runs;
  const el = node as HTMLElement;
  const tag = el.tagName.toUpperCase();
  if (tag === "BR") {
    runs.push(new TextRun({ break: 1 }));
    return runs;
  }
  const nextStyle = {
    bold: style.bold || tag === "STRONG" || tag === "B",
    italics: style.italics || tag === "EM" || tag === "I",
  };
  el.childNodes.forEach((child) => {
    runs.push(...collectTextRuns(child, nextStyle));
  });
  return runs;
}

function htmlToDocxParagraphs(html: string): Paragraph[] {
  if (!html || isRichTextEmpty(html)) {
    return [
      new Paragraph({
        children: [new TextRun({ text: "（未填写 / Not provided）", italics: true, color: "94A3B8" })],
      }),
    ];
  }
  const doc = new DOMParser().parseFromString(html, "text/html");
  const paragraphs: Paragraph[] = [];

  const blockTags = new Set(["P", "DIV", "LI", "H1", "H2", "H3"]);
  doc.body.childNodes.forEach((node) => {
    if (node.nodeType === Node.ELEMENT_NODE) {
      const el = node as HTMLElement;
      const tag = el.tagName.toUpperCase();
      if (tag === "UL" || tag === "OL") {
        el.querySelectorAll("li").forEach((li) => {
          const runs = collectTextRuns(li);
          paragraphs.push(
            new Paragraph({
              children: [new TextRun({ text: "• ", bold: true }), ...runs],
              spacing: { after: 120 },
            })
          );
        });
        return;
      }
      if (blockTags.has(tag) || el.textContent?.trim()) {
        const runs = collectTextRuns(el);
        if (runs.length) {
          paragraphs.push(new Paragraph({ children: runs, spacing: { after: 160 } }));
        }
      }
    } else if (node.textContent?.trim()) {
      paragraphs.push(
        new Paragraph({ children: [new TextRun(node.textContent || "")], spacing: { after: 160 } })
      );
    }
  });

  if (!paragraphs.length) {
    paragraphs.push(
      new Paragraph({ children: [new TextRun(stripHtml(html))], spacing: { after: 160 } })
    );
  }
  return paragraphs;
}

function metaTableRows(meta: BriefExportMeta, brief: InnovationBrief): TableRow[] {
  const rows: [string, string][] = [
    ["Team / 队伍", meta.teamName],
    ["Project / 项目", meta.projectName],
  ];
  if (meta.challengeCategory) rows.push(["Category / 类别", meta.challengeCategory]);
  if (meta.teacherName) rows.push(["Teacher / 带队老师", meta.teacherName]);
  rows.push(["Completion / 完成度", `${brief.completion_count} / 10`]);
  rows.push(["Exported / 导出时间", formatExportDate()]);

  return rows.map(
    ([label, value]) =>
      new TableRow({
        children: [
          new TableCell({
            width: { size: 35, type: WidthType.PERCENTAGE },
            children: [new Paragraph({ children: [new TextRun({ text: label, color: "64748B", size: 20 })] })],
            borders: noBorders(),
          }),
          new TableCell({
            width: { size: 65, type: WidthType.PERCENTAGE },
            children: [new Paragraph({ children: [new TextRun({ text: value, bold: true, size: 22 })] })],
            borders: noBorders(),
          }),
        ],
      })
  );
}

function noBorders() {
  const none = { style: BorderStyle.NONE, size: 0, color: "FFFFFF" };
  return { top: none, bottom: none, left: none, right: none };
}

export async function exportBriefPdf(brief: InnovationBrief, meta: BriefExportMeta): Promise<void> {
  const wrapper = document.createElement("div");
  wrapper.style.position = "fixed";
  wrapper.style.left = "-10000px";
  wrapper.style.top = "0";
  wrapper.style.width = "794px";
  wrapper.style.background = "#ffffff";
  wrapper.innerHTML = buildExportHtml(brief, meta);
  document.body.appendChild(wrapper);

  const filename = `${safeFilename(meta.teamName)}_Innovation_Brief.pdf`;

  try {
    const html2pdf = (await import("html2pdf.js")).default;
    await html2pdf()
      .set({
        margin: [12, 12, 14, 12],
        filename,
        image: { type: "jpeg", quality: 0.98 },
        html2canvas: { scale: 2, useCORS: true, letterRendering: true },
        jsPDF: { unit: "mm", format: "a4", orientation: "portrait" },
        pagebreak: { mode: ["avoid-all", "css", "legacy"] },
      })
      .from(wrapper.querySelector(".brief-export-root") as HTMLElement)
      .save();
  } finally {
    document.body.removeChild(wrapper);
  }
}

export async function exportBriefDocx(brief: InnovationBrief, meta: BriefExportMeta): Promise<void> {
  const children: (Paragraph | Table)[] = [
    new Paragraph({
      alignment: AlignmentType.CENTER,
      spacing: { after: 80 },
      children: [
        new TextRun({
          text: "CONRAD CHALLENGE · STEMHUB",
          size: 18,
          color: "64748B",
          allCaps: true,
        }),
      ],
    }),
    new Paragraph({
      heading: HeadingLevel.TITLE,
      alignment: AlignmentType.CENTER,
      children: [new TextRun({ text: "Innovation Brief", bold: true, size: 48, color: "2563EB" })],
      spacing: { after: 60 },
    }),
    new Paragraph({
      alignment: AlignmentType.CENTER,
      spacing: { after: 240 },
      children: [new TextRun({ text: "创新简报", size: 28, color: "7C3AED" })],
    }),
    new Table({
      width: { size: 100, type: WidthType.PERCENTAGE },
      rows: metaTableRows(meta, brief),
    }),
    new Paragraph({ text: "", spacing: { after: 300 } }),
  ];

  BRIEF_QUESTIONS.forEach((q) => {
    const val = String(brief[q.id] || "");
    children.push(
      new Paragraph({
        spacing: { before: 280, after: 120 },
        border: {
          bottom: { color: "7C3AED", size: 12, style: BorderStyle.SINGLE },
        },
        children: [
          new TextRun({ text: `Q${q.q}. `, bold: true, size: 26, color: "7C3AED" }),
          new TextRun({ text: q.titleEn, bold: true, size: 26 }),
        ],
      }),
      new Paragraph({
        spacing: { after: 160 },
        children: [new TextRun({ text: q.titleZh, italics: true, color: "64748B", size: 20 })],
      }),
      ...htmlToDocxParagraphs(val)
    );
  });

  children.push(
    new Paragraph({
      alignment: AlignmentType.CENTER,
      spacing: { before: 400 },
      children: [
        new TextRun({
          text: "Conrad Challenge Innovation Brief · STEMHUB Operations Export",
          size: 18,
          color: "94A3B8",
          italics: true,
        }),
      ],
    })
  );

  const doc = new Document({
    sections: [{ properties: {}, children }],
  });

  const blob = await Packer.toBlob(doc);
  saveAs(blob, `${safeFilename(meta.teamName)}_Innovation_Brief.docx`);
}
