# Generated by Django 4.2.30 on 2026-06-21 12:54

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        ("teams", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Deliverable",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("title", models.CharField(max_length=300, verbose_name="标题")),
                (
                    "type",
                    models.CharField(
                        choices=[
                            ("file", "文件"),
                            ("link", "链接"),
                            ("figma", "Figma"),
                            ("video", "视频"),
                            ("document", "文档"),
                        ],
                        default="file",
                        max_length=20,
                        verbose_name="类型",
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("not_started", "未开始"),
                            ("in_progress", "进行中"),
                            ("submitted", "已提交"),
                            ("needs_revision", "需修改"),
                            ("approved", "已通过"),
                            ("overdue", "已逾期"),
                        ],
                        default="not_started",
                        max_length=20,
                        verbose_name="状态",
                    ),
                ),
                (
                    "due_date",
                    models.DateField(blank=True, null=True, verbose_name="截止日期"),
                ),
                (
                    "submitted_at",
                    models.DateTimeField(blank=True, null=True, verbose_name="提交时间"),
                ),
                ("file_url", models.URLField(blank=True, verbose_name="文件链接")),
                ("external_link", models.URLField(blank=True, verbose_name="外部链接")),
                ("score", models.FloatField(blank=True, null=True, verbose_name="评分")),
                ("max_score", models.FloatField(default=10, verbose_name="满分")),
                ("review_comment", models.TextField(blank=True, verbose_name="审核意见")),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "owner",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="owned_deliverables",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="负责人",
                    ),
                ),
                (
                    "reviewer",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="reviewed_deliverables",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="审核人",
                    ),
                ),
                (
                    "stage",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="deliverables",
                        to="teams.stage",
                    ),
                ),
                (
                    "team",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="deliverables",
                        to="teams.team",
                    ),
                ),
            ],
            options={
                "verbose_name": "交付物",
                "verbose_name_plural": "交付物",
                "ordering": ["stage__order", "due_date"],
            },
        ),
    ]
