# Generated by Django 5.2.15 on 2026-07-13 12:36

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("accounts", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="user",
            name="role",
            field=models.CharField(
                choices=[
                    ("student", "Student"),
                    ("teacher", "Teacher"),
                    ("operations", "Operations"),
                ],
                default="student",
                max_length=20,
            ),
        ),
    ]
