# Generated by Django 4.2.30 on 2026-06-21 12:54

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Stage",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=200, verbose_name="阶段名称")),
                ("order", models.IntegerField(default=0, verbose_name="排序")),
                ("description", models.TextField(blank=True, verbose_name="描述")),
                (
                    "start_date",
                    models.DateField(blank=True, null=True, verbose_name="开始日期"),
                ),
                (
                    "end_date",
                    models.DateField(blank=True, null=True, verbose_name="结束日期"),
                ),
            ],
            options={
                "verbose_name": "阶段",
                "verbose_name_plural": "阶段",
                "ordering": ["order"],
            },
        ),
        migrations.CreateModel(
            name="Team",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("team_name", models.CharField(max_length=200, verbose_name="队伍名称")),
                (
                    "project_name_cn",
                    models.CharField(max_length=300, verbose_name="项目中文名"),
                ),
                (
                    "project_name_en",
                    models.CharField(blank=True, max_length=300, verbose_name="项目英文名"),
                ),
                (
                    "track",
                    models.CharField(
                        choices=[
                            ("health", "健康与营养"),
                            ("energy", "能源与环境"),
                            ("cyber", "网络安全"),
                            ("aerospace", "航空航天"),
                            ("special", "特别赛道"),
                        ],
                        default="health",
                        max_length=20,
                        verbose_name="赛道",
                    ),
                ),
                (
                    "season",
                    models.CharField(
                        default="2026-2027", max_length=50, verbose_name="赛季"
                    ),
                ),
                (
                    "risk_status",
                    models.CharField(
                        choices=[
                            ("normal", "正常推进"),
                            ("attention", "需要关注"),
                            ("critical", "需要介入"),
                        ],
                        default="normal",
                        max_length=20,
                        verbose_name="风险状态",
                    ),
                ),
                ("description", models.TextField(blank=True, verbose_name="描述")),
                (
                    "deliverable_completion_rate",
                    models.FloatField(default=0, verbose_name="交付完成率"),
                ),
                ("mentor_score", models.FloatField(default=0, verbose_name="导师评分")),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "academic_admin",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="academic_teams",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="教务老师",
                    ),
                ),
                (
                    "current_stage",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="teams",
                        to="teams.stage",
                        verbose_name="当前阶段",
                    ),
                ),
                (
                    "lead_mentor",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="mentor_teams",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="主导师",
                    ),
                ),
                (
                    "project_manager",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="managed_teams",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="项目经理",
                    ),
                ),
            ],
            options={
                "verbose_name": "队伍",
                "verbose_name_plural": "队伍",
                "ordering": ["-updated_at"],
            },
        ),
        migrations.CreateModel(
            name="Student",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=100, verbose_name="姓名")),
                (
                    "english_name",
                    models.CharField(blank=True, max_length=100, verbose_name="英文名"),
                ),
                (
                    "grade",
                    models.CharField(blank=True, max_length=50, verbose_name="年级"),
                ),
                (
                    "school",
                    models.CharField(blank=True, max_length=200, verbose_name="学校"),
                ),
                (
                    "role_in_team",
                    models.CharField(blank=True, max_length=100, verbose_name="队内角色"),
                ),
                (
                    "parent_contact",
                    models.CharField(blank=True, max_length=100, verbose_name="家长联系方式"),
                ),
                ("notes", models.TextField(blank=True, verbose_name="备注")),
                (
                    "team",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="members",
                        to="teams.team",
                        verbose_name="队伍",
                    ),
                ),
            ],
            options={
                "verbose_name": "学生",
                "verbose_name_plural": "学生",
            },
        ),
    ]
