# Generated by Django 4.2.30 on 2026-06-21 14:02

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("teams", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="team",
            name="budget_doc",
            field=models.CharField(blank=True, max_length=500, verbose_name="项目预算"),
        ),
        migrations.AddField(
            model_name="team",
            name="ceo_status",
            field=models.CharField(blank=True, max_length=50, verbose_name="CEO"),
        ),
        migrations.AddField(
            model_name="team",
            name="cfo_status",
            field=models.CharField(blank=True, max_length=50, verbose_name="CFO"),
        ),
        migrations.AddField(
            model_name="team",
            name="classroom",
            field=models.CharField(blank=True, max_length=200, verbose_name="预定教室"),
        ),
        migrations.AddField(
            model_name="team",
            name="cmo_status",
            field=models.CharField(blank=True, max_length=50, verbose_name="CMO"),
        ),
        migrations.AddField(
            model_name="team",
            name="cpo_status",
            field=models.CharField(blank=True, max_length=50, verbose_name="CPO"),
        ),
        migrations.AddField(
            model_name="team",
            name="crm_number",
            field=models.CharField(blank=True, max_length=100, verbose_name="CRM申请编号"),
        ),
        migrations.AddField(
            model_name="team",
            name="cto_status",
            field=models.CharField(blank=True, max_length=50, verbose_name="CTO"),
        ),
        migrations.AddField(
            model_name="team",
            name="offline_city",
            field=models.CharField(blank=True, max_length=100, verbose_name="线下城市"),
        ),
        migrations.AddField(
            model_name="team",
            name="offline_end",
            field=models.DateField(blank=True, null=True, verbose_name="线下结束"),
        ),
        migrations.AddField(
            model_name="team",
            name="offline_lead",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="offline_lead_teams",
                to=settings.AUTH_USER_MODEL,
                verbose_name="线下带队",
            ),
        ),
        migrations.AddField(
            model_name="team",
            name="offline_start",
            field=models.DateField(blank=True, null=True, verbose_name="线下启动"),
        ),
        migrations.AddField(
            model_name="team",
            name="okr_link",
            field=models.CharField(blank=True, max_length=500, verbose_name="队伍OKR节点"),
        ),
        migrations.AddField(
            model_name="team",
            name="project_log_doc",
            field=models.CharField(blank=True, max_length=500, verbose_name="项目日志"),
        ),
        migrations.AddField(
            model_name="team",
            name="project_proposal",
            field=models.CharField(blank=True, max_length=500, verbose_name="项目立项书"),
        ),
        migrations.AddField(
            model_name="team",
            name="rnd_approved",
            field=models.BooleanField(default=False, verbose_name="研发审批发放"),
        ),
        migrations.AddField(
            model_name="team",
            name="stage1_progress",
            field=models.FloatField(default=0, verbose_name="第一阶段进度"),
        ),
        migrations.AddField(
            model_name="team",
            name="stage2_progress",
            field=models.FloatField(default=0, verbose_name="第二阶段进度"),
        ),
        migrations.AddField(
            model_name="team",
            name="stage3_progress",
            field=models.FloatField(default=0, verbose_name="第三阶段进度"),
        ),
        migrations.AddField(
            model_name="team",
            name="task_tracking_doc",
            field=models.CharField(blank=True, max_length=500, verbose_name="任务跟踪表"),
        ),
        migrations.AddField(
            model_name="team",
            name="team_chat_group",
            field=models.CharField(blank=True, max_length=500, verbose_name="队伍群聊"),
        ),
        migrations.AddField(
            model_name="team",
            name="website_status",
            field=models.CharField(blank=True, max_length=50, verbose_name="产品网站完成"),
        ),
        migrations.AlterField(
            model_name="team",
            name="lead_mentor",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="mentor_teams",
                to=settings.AUTH_USER_MODEL,
                verbose_name="带队教练",
            ),
        ),
        migrations.AlterField(
            model_name="team",
            name="project_manager",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="managed_teams",
                to=settings.AUTH_USER_MODEL,
                verbose_name="项目运营老师",
            ),
        ),
        migrations.AlterField(
            model_name="team",
            name="track",
            field=models.CharField(
                choices=[
                    ("health", "营养健康"),
                    ("energy", "能源环境"),
                    ("cyber", "网络安全"),
                    ("aerospace", "航空航天"),
                    ("water", "水可持续"),
                    ("special", "特别赛道"),
                ],
                default="health",
                max_length=20,
                verbose_name="赛道",
            ),
        ),
    ]
